#!/bin/bash

SCRIPT_DIR=`dirname "$0"`
OUT_DIR=${1:-.}

while true
do
  output=`node "$SCRIPT_DIR/export-entry.js" "$OUT_DIR"`

  code="$?"
  case "$code" in
  0)
    echo Finished
    ;;
  20)
    echo None left
    sleep 10
    ;;
  *)
    echo $output
    exit "$code"
    ;;
  esac
done
