#!/bin/bash

SCRIPT="$0"
while [ -L "$SCRIPT" ]
do
  SCRIPT=`readlink "$0"`
done

SCRIPT_DIR=`dirname "$SCRIPT"`
OUT_DIR=${1:-.}

while true
do
  output=`node "$SCRIPT_DIR/export-entry.js" "$OUT_DIR"`

  code="$?"
  case "$code" in
  0)
    echo Finished
    ;;
  20)
    echo None left
    sleep 10
    ;;
  *)
    echo $output
    exit "$code"
    ;;
  esac
done
